apiVersion: v1
kind: Secret
metadata:
  name: video-conference-service-secrets
type: Opaque
data:
  jwt-secret: YmFzZTY0ZW5jb2RlZC1qd3Qtc2VjcmV0
  livekit-api-key: YmFzZTY0ZW5jb2RlZC1saXZla2l0LWFwaS1rZXk=
  livekit-api-secret: YmFzZTY0ZW5jb2RlZC1saXZla2l0LWFwaS1zZWNyZXQ=
