apiVersion: v1
kind: Service
metadata:
  name: video-conference-service
  labels:
    app: video-conference-service
spec:
  selector:
    app: video-conference-service
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
  type: ClusterIP
